"""
Django settings for takeone project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILE_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u!0q&30u)d8@s83_6s%pjpivb6^axuelgld08-csxj%$#nsx_y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'crispy_forms',
    'registration',
    'django_twilio',
    'stripe',
    'import_export',

    'newsletter',
    'photographer',
    'reserve',
    'blog',
    'sms',
    'userprofile',
    'book',
    'careerlab',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'takeone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'takeone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'takeone',
        'USER': 'byy',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# registration redux
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
LOGIN_REDIRECT_URL = '/profile'
SITE_ID = 1
SITE_URL = 'http://127.0.0.1:8000'
SITE_EMAIL = 'hello@brytephoto.com'


# crispy form
CRISPY_TEMPLATE_PACK = 'bootstrap3'


# email 
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'hello@brytephoto.com'
EMAIL_HOST_PASSWORD = 'YCombinator!'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(FILE_DIR, "static"),
]

STATIC_ROOT = 'staticfiles'

MEDIA_ROOT = 'mediafiles'

# Time Zone
TIMEZONE = 'America/New_York'

# twilio
TWILIO_ACCOUNT_SID = 'ACa508a195425ca7341d5469a54a91cb36'
TWILIO_AUTH_TOKEN = '4005b7c244086f9986d6375b2b7530e3'
BEN_CELL = '+13109139124'
TWILIO_CELL = '+13137698688'


# strip
STRIPE_SECRET_KEY = 'sk_test_WOCKGbny1dkmA6NsOQARm0a0'
STRIPE_PUBLISHABLE_KEY = 'pk_test_mpoNaxCzG3mO8CqAYE9OWzng'
CLIENT_ID = 'ca_7ogFGpVd6vsmx5rmZ8zbRgyokyCnzOU0'
COMMISSION = 0.2

# mixpanel
MIXPANEL_TOKEN = 'b27c2c4d1dddc024a8c4b60b153f2968'

# dropbox
DROPBOX_TOKEN = 'Ke0AGlcGduAAAAAAAAAAFD8Nh_z7mnFNokERrunQtMoQ3xwusnSCpT0ZRNckEbvt'

DROPBOX_PATH = os.path.join('/', 'Test')
DROPBOX_PHOTO = os.path.join('/', 'TEST PHOTO')


# sendgrid
SENDGRID_KEY = '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'

