# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smser',
            name='use_service',
            field=models.BooleanField(default=False),
        ),
    ]
