"""
Django settings for takeone project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import base
import dj_database_url

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
    }
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/


# Parse database configuration from $DATABASE_URL

DATABASES['default'] = dj_database_url.config()

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers


# Static asset configuration
STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'

MEDIA_ROOT = 'mediafiles'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(FILE_DIR, "static"),
]

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'


# try:
#     from .local_settings import *
# except ImportError:
#     pass


# security
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True


# Amazon S3
if not DEBUG:
   AWS_STORAGE_BUCKET_NAME = "take-one"
   AWS_ACCESS_KEY_ID = "AKIAI5IZ4TEQRKUGV24A"
   AWS_SECRET_ACCESS_KEY = "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"
   AWS_PRELOAD_METADATA = True
   STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

   S3_URL = 'http://%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
   STATIC_URL = S3_URL + 'static/'
   STATIC_ROOT = STATIC_URL

   MEDIA_URL = S3_URL + 'media/'
   MEDIA_ROOT = MEDIA_URL
