# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0032_remove_photographer_dropbox_status'),
        ('careerlab', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nextshoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextshoot_photographer', to='photographer.Photographer')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
