# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0003_nextshoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='shoot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
