# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0004_timeslot_shoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hash_id',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
