# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0005_booking_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='overbook_volumn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
