# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0006_timeslot_overbook_volumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
