# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0007_timeslot_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
