# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0009_remove_timeslot_overbook_volumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='shoot',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
