# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0010_auto_20160509_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='shoot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
