# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0011_auto_20160509_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropbox_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
