# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0012_booking_dropbox_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='shoot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
