# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0013_auto_20160605_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='school',
            field=models.CharField(default='not assigned', max_length=60),
        ),
    ]
