# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0014_nextshoot_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
