# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0014_nextshoot_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='shoot',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Nextshoot'),
        ),
    ]
