# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0017_headshotimage_is_deliverable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headshotimage',
            old_name='url',
            new_name='original_url',
        ),
        migrations.RemoveField(
            model_name='headshotimage',
            name='is_thumbnail',
        ),
        migrations.AddField(
            model_name='headshotimage',
            name='thumbnail_url',
            field=models.CharField(default='default', max_length=80),
            preserve_default=False,
        ),
    ]
