# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0021_auto_20160617_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepurchase',
            name='charge_successful',
            field=models.BooleanField(default=True),
        ),
    ]
