# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0022_imagepurchase_charge_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepurchase',
            name='option',
            field=models.CharField(choices=[('oh', 'Original Headshot'), ('st', 'Standard Touchup'), ('pt', 'Premium Touchup'), ('pp', 'Passport Package')], default='og', max_length=2),
        ),
    ]
