# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0023_auto_20160620_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotimage',
            name='is_upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
