# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0024_headshotimage_is_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotimage',
            name='is_fullsize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headshotimage',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
