# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0025_auto_20160622_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headshotimage',
            name='is_upgrade',
        ),
    ]
