# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0026_remove_headshotimage_is_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotimage',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
