# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0027_auto_20160622_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotimage',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
