# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0028_headshotimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepurchase',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagepurchase',
            name='option',
            field=models.CharField(choices=[('oh', 'Original Headshot'), ('st', 'Standard Touchup'), ('pt', 'Premium Touchup'), ('pp', 'Passport Package')], default='oh', max_length=2),
        ),
    ]
