# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0030_auto_20160623_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headshotimage',
            name='original_url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='headshotimage',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
