# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0031_auto_20160623_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_up',
            field=models.BooleanField(default=False),
        ),
    ]
