# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0037_auto_20160703_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
