# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0039_remove_timeslot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
