# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0041_auto_20160712_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='headshot_for',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='professional_path',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='school_year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
