# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0042_auto_20160712_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='headshot_for',
            new_name='area_of_study',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='school_year',
            new_name='program_progress',
        ),
    ]
