# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0046_signup_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalHeadshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('raw_url', models.CharField(blank=True, max_length=80, null=True)),
                ('deliverable_url', models.CharField(blank=True, max_length=80, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerlab.Booking')),
            ],
        ),
    ]
