# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0047_originalheadshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalheadshot',
            name='hash_id',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
