# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0048_originalheadshot_hash_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadshotOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerlab.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='HeadshotPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchup', models.PositiveSmallIntegerField(choices=[(1, 'The Just Enough'), (2, 'The Step Ahead'), (3, 'The Full Suite')], default=1)),
                ('background', models.PositiveSmallIntegerField(choices=[(1, 'Professional White'), (2, 'Mild Gray'), (3, 'Traditional Blue')], default=1)),
                ('prints', models.BooleanField(default=False)),
                ('frame', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='careerlab.OriginalHeadshot')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerlab.HeadshotOrder')),
            ],
        ),
    ]
