# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0049_headshotorder_headshotpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careerlab.HeadshotOrder'),
        ),
    ]
