# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0050_auto_20160914_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
