# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0051_auto_20160914_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotpurchase',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
