# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0052_headshotpurchase_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='background',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Professional White'), (2, 'Mild Gray'), (3, 'Traditional Blue'), (4, 'Awesome Black')], default=1),
        ),
    ]
