# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0054_auto_20160920_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headshotpurchase',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='headshotpurchase',
            name='prints',
        ),
        migrations.AddField(
            model_name='headshotpurchase',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No Package'), (2, 'Wallet Prints'), (3, 'Friends and Family'), (4, 'Complete Collection'), (5, 'Premium Framed Print')], default=1),
        ),
    ]
