# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0055_auto_20160920_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotorder',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headshotorder',
            name='copied',
            field=models.BooleanField(default=False),
        ),
    ]
