# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0057_headshotorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotpurchase',
            name='special_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headshotpurchase',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerlab.OriginalHeadshot'),
        ),
    ]
