# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0058_auto_20160921_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalheadshot',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='originalheadshot',
            name='copied',
            field=models.BooleanField(default=False),
        ),
    ]
