# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0060_auto_20160922_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headshotorder',
            name='charged',
        ),
        migrations.RemoveField(
            model_name='headshotorder',
            name='copied',
        ),
        migrations.AddField(
            model_name='headshotpurchase',
            name='charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headshotpurchase',
            name='copied',
            field=models.BooleanField(default=False),
        ),
    ]
