# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0061_auto_20160922_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='touchup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Basic'), (3, 'Professional'), (4, 'Customized')], default=1),
        ),
    ]
