# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0062_auto_20160927_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotpurchase',
            name='hash_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
