# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0063_headshotpurchase_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotpurchase',
            name='raw_url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
