# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0064_headshotpurchase_raw_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='touchup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Basic'), (3, 'Standard'), (4, 'Customized')], default=1),
        ),
    ]
