# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0066_booking_cust_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cust_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No free nor buy'), (2, 'Free only'), (3, 'Paid customer')], null=True),
        ),
    ]
