# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0068_auto_20161012_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotpurchase',
            name='copied_to_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headshotpurchase',
            name='copied_to_touchup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headshotpurchase',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
