# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0069_auto_20161012_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='max_volumn',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
