# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0070_nextshoot_max_volumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotorder',
            name='touchup_folder',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
