# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0072_auto_20161017_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='is_serving',
            field=models.BooleanField(default=True),
        ),
    ]
