# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0073_nextshoot_is_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='headshotorder',
            name='shipping_days',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
