# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0074_headshotorder_shipping_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headshotorder',
            name='shipping_days',
        ),
        migrations.AddField(
            model_name='headshotorder',
            name='express_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
