# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0077_auto_20161022_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='basic_price',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='nextshoot',
            name='customized_price',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='nextshoot',
            name='professional_price',
            field=models.PositiveSmallIntegerField(default=11),
        ),
    ]
