# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0081_auto_20161029_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='touchup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Minimum'), (2, 'Basic'), (3, 'Standard'), (4, 'Customized')], default=1),
        ),
    ]
