# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0082_auto_20161112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='special_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
