# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0083_auto_20161112_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headshotpurchase',
            name='touchup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Plus'), (4, 'Customized')], default=1),
        ),
    ]
