# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0084_auto_20161119_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
