# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0085_booking_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.FloatField(default=1.0),
        ),
    ]
