# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0086_auto_20161225_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_sub',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cust_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No free nor buy'), (2, 'Free only'), (3, 'Paid customer'), (4, 'Exclusive member')], null=True),
        ),
        migrations.AlterField(
            model_name='headshotpurchase',
            name='background',
            field=models.PositiveSmallIntegerField(choices=[(1, 'White'), (2, 'Polished Gray'), (3, 'Designer Bricks'), (4, 'Sanguine Blue'), (5, 'Nighttime Black'), (6, 'Light Cream'), (7, 'Frosty Blue'), (8, 'Riverside Blue'), (9, 'Airy Gray'), (10, 'Vibrant Orange'), (11, '31st Story Office'), (12, 'Eclectic Bookcase'), (13, 'Firm Hallway'), (14, 'Urban Walkway'), (15, 'Traditional Blue'), (16, 'Bruno Brown'), (17, 'Shadowy Gray'), (18, 'Campus Green'), (19, 'Fresh Air')], default=1),
        ),
    ]
