# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0087_auto_20170129_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
