# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0089_signup_is_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='hash_id',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
