# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0091_nextshoot_noshow_to_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextshoot',
            old_name='noshow_to_signup',
            new_name='noshow_signup',
        ),
        migrations.AddField(
            model_name='nextshoot',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
