# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0092_auto_20170208_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
