# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0093_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropbox_folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='upgrade_folder_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
