# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_price_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
