# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20160214_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_photography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='is_videography',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
