# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20160215_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='level',
        ),
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('re', 'Real Estate'), ('sb', 'Small Business')], default='re', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
    ]
