# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20160215_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
