# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0028_auto_20160222_2125'),
        ('newsletter', '0009_auto_20160215_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_promotional',
        ),
        migrations.AddField(
            model_name='price',
            name='photographer',
            field=models.ManyToManyField(blank=True, to='photographer.Photographer'),
        ),
    ]
