# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20160222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='shared_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
