# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20160225_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='price',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
