# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_remove_price_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'School'), (2, 'For profit business'), (3, 'Non profit business')])),
                ('amount', models.PositiveSmallIntegerField(choices=[(1, 'Less than 50'), (2, '50 - 300'), (3, '300 - 600'), (4, 'Greater than 600')])),
                ('question', models.TextField()),
            ],
        ),
    ]
