# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_contactsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsale',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'School'), (2, 'For profit business'), (3, 'Non profit business'), (4, 'Individual')]),
        ),
    ]
