# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_auto_20160526_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
            ],
        ),
    ]
