# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_contacthelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsale',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
