# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerlab', '0015_signup_shoot'),
        ('newsletter', '0018_contactsale_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('family_email', models.EmailField(max_length=254)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='careerlab.Booking')),
            ],
        ),
    ]
