# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_familycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contactsale',
            name='question',
        ),
    ]
