# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_auto_20160629_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=60)),
                ('year_in_school', models.CharField(max_length=20)),
                ('dslr_model', models.CharField(max_length=50)),
                ('prev_job', models.CharField(max_length=200)),
                ('photo_exp', models.CharField(max_length=50)),
                ('num_of_shoot', models.CharField(max_length=100)),
                ('portfolio_link', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
