# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0021_photographerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerapplication',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
