# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_stripe_id'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 2, 31, 15, 965107, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, default='+3109139124', max_length=15),
            preserve_default=False,
        ),
    ]
