# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20160128_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
    ]
