# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20160125_0254'),
        ('reserve', '0004_auto_20160128_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Price'),
        ),
    ]
