# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20160128_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
