# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_reservation_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 29, 3, 14, 17, 348713, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
