# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20160222_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='business_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_range',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Price'),
        ),
    ]
