# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_auto_20160225_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
