# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_auto_20160228_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropbox_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
