# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photographer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('profile', models.ImageField(null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photographer.models.image_upload_to)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photographer')),
            ],
        ),
    ]
