# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 05:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0003_photographer_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 7, 5, 19, 26, 889174, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
