# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_rating_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='total_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], null=True),
        ),
    ]
