# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0008_package_packagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='highest_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='lowest_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
