# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0010_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='specialty_text',
            field=models.CharField(choices=[('hs', 'Headshot'), ('od', 'Outdoor'), ('vt', 'Vintage'), ('id', 'Indoor'), ('pt', 'Portrait')], max_length=120),
        ),
    ]
