# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0012_photographer_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(default='test@abc.com', max_length=254),
            preserve_default=False,
        ),
    ]
