# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0014_auto_20160126_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='is_student',
        ),
    ]
