# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0015_remove_photographer_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='location',
            field=models.CharField(default='Providence, RI', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='school',
            field=models.CharField(default='Brown University', max_length=50),
            preserve_default=False,
        ),
    ]
