# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0016_auto_20160202_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='highest_price',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='lowest_price',
        ),
    ]
