# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0017_auto_20160213_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
