# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0018_auto_20160213_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
