# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0019_auto_20160213_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='photography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographer',
            name='videography',
            field=models.BooleanField(default=False),
        ),
    ]
