# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0020_auto_20160213_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='scope',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
