# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0021_auto_20160213_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
