# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0022_photographer_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
