# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20160215_0258'),
        ('photographer', '0026_remove_photographer_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographerprice',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photographer'),
        ),
        migrations.AddField(
            model_name='photographerprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Price'),
        ),
    ]
