# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0027_auto_20160222_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerprice',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='photographerprice',
            name='price',
        ),
        migrations.DeleteModel(
            name='PhotographerPrice',
        ),
    ]
