# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0028_auto_20160222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
