# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0029_photographer_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='dropbox_acct',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
