# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 17, 45, 52, 958846, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
