# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_stripe_id'),
        ('blog', '0003_blog_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile')),
            ],
        ),
    ]
