# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160213_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_user_id',
        ),
    ]
