# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0032_remove_photographer_dropbox_status'),
        ('book', '0002_timeslot_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextShoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photographer.Photographer')),
            ],
        ),
    ]
