# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_nextshoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextshoot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 22, 22, 24, 27, 514042, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
